apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../tasks
- pipeline.yaml
- pvc.yaml

patches:
- target:
    kind: Task
  patch: |-
    - op: replace
      path: /spec/steps/0/image
      value: quay.io/redhat-appstudio/appstudio-utils:test