on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test something
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      - name: yaml-action-setup
        id: hello
        uses: ./
        with:
          yaml-path: './openshift'
          is_dir: 'true'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"