on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test something
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: yaml-action-setup
        id: hello
        uses: ./
        with:
          yaml-path: './openshift/template.yaml'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"