on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test something
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      - name: Install kubeval cli
        uses: sawood14012/setup-kubeval-cli@v1.1
        with:
          version: '0.16.1'
      - name: yaml-action-setup-test-1
        uses: ./
        with:
          files: './openshift'
      - name: yaml-action-setup-test-2
        uses: ./
        with:
          files: './init.yaml'
          non_template: 'true'
      - name: yaml-action-setup-test-3
        uses: ./
        with:
          files: './pvc.yaml'
          kubernetes_mode: 'true'
          non_template: 'true'
      - name: yaml-action-setup-test-4
        uses: ./
        with:
          files: './non_temp'
          non_template: 'true'
      
     